// <auto-generated />
namespace Spikes.Migrations.DataMigrations.AutoMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MergeBaseModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeBaseModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201501012025196_Merge BaseModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
