// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Spikes.Migrations.DataMigrations.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MergeBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201412280947272_MergeBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
