// <auto-generated />
namespace Spikes.Migrations.BaseDataMigrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserRoleaddalternatekeycol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRoleaddalternatekeycol));
        
        string IMigrationMetadata.Id
        {
            get { return "201501012023566_UserRole add alternate key col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
