//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyCompany("ECA")]
[assembly: AssemblyProduct("Eca.Commons")]
[assembly: AssemblyCopyright("Copyright ©2006 ECA")]
[assembly: AssemblyTitle("Eca.Commons")]
[assembly: AssemblyVersion("1.0.1520.0")]
[assembly: AssemblyFileVersion("1.0.1520.0")]


