//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyCompany("ECA")]
[assembly: AssemblyProduct("Eca.CoreLib")]
[assembly: AssemblyCopyright("Copyright ©2006 ECA")]
[assembly: AssemblyTitle("Eca.CoreLib")]
[assembly: AssemblyDescription("Eca Core Library")]
[assembly: AssemblyVersion("1.0.635.0")]
[assembly: AssemblyFileVersion("1.0.635.0")]


